name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      IMAGE_NAME: llmrouter
      IMAGE_REPO: ${{ vars.DOCKERHUB_NAMESPACE }}/llmrouter

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for tests
        run: docker build -t $IMAGE_NAME:ci-test .

      - name: Smoke test container
        run: |
          docker run -d --rm -p 8000:8000 \
            -e LLMROUTER_MODEL_INDEX_URL="file:///app/generated/model_index.json" \
            -e LLMROUTER_PROVIDERS="echo" \
            --name llmrouter-test $IMAGE_NAME:ci-test
          for i in {1..10}; do
            if curl --fail http://localhost:8000/ > /dev/null; then
              break
            fi
            sleep 1
          done
          curl --fail -X POST http://localhost:8000/v1/chat/completions \
            -H 'Content-Type: application/json' \
            -d '{"messages": [{"role": "user", "content": "ping"}]}'
          docker stop llmrouter-test

      - name: Log in to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ github.sha }}

      - name: Update Docker Hub README
        if: github.event_name == 'push'
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_NAMESPACE }}/llmrouter
          short-description: llmrouter multi-provider router
          readme-filepath: README.md
