name: Build Model Catalog

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      NVIDIA_NIM_KEY: ${{ secrets.NVIDIA_NIM_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate model catalog
        run: |
          python scripts/build_free_model_catalog.py --providers "groq,openrouter,nvidia_nim" --output generated/model_index.json --pretty

      - name: Upload catalog artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-index
          path: generated/model_index.json
